### PR TITLE
API para mensagem MovementPeriodStatus

### PR DESCRIPTION
**Pull request by williamsilvestre**
Mensagem: MovementPeriodStatus
Schema: MovementPeriodStatus_1_000
Segmento: Saúde
Produto: HRC

### CODE REVIEW

**Comment by reisaolucas** [comment]
Testing comment via API.

**Comment by reisaolucas** [comment]
Testing 2

**Comment by reisaolucas** [comment]
Testing 2

**Comment by reisaolucas** [comment]
Testing blabla

**Comment by reisaolucas** [comment]
Testing blabla

**Comment by reisaolucas** [comment]
Testing blabla

**Comment by reisaolucas** [comment]
https://api.travis-ci.org/v3/job/459848043/log.txt

**Comment by reisaolucas** [comment]
YwFbRmtrJLszTW77LOOa3pdnzRijhNP457FIrL7QAaf2CA0I0iNEwjbXdT67xvFy7cDxCvWGfSZKZokK8AYhL3smohjD6wBvhAil7g4IqdIjURgvlk23rXK3X9pGDwArg8vnBa2TMucJ0OhGGUQfH4z76yiEgi4T1VSFbnZIEBDm6jVrPAiLonYqYUGHSMZzWROa1lPnPerDwEBrfERHN06oYIAzJ7pDd5ZsqHYDVhGGXAsym5y2NT0izqPaZrvZawjGdNMgLXR9CFUxtVA28IDnanr9ubTNTmzLh77jLPHOqY2LJeJNl4svxWjwuSc3O35mmXdrwBUdMgHoru8Gvvz81P71w2sfxJamD6gFEfzvRuIFDLFIl1cTNzLjeXwRpmBxAa2MgpInbYRmTbUEp1isY3TxGaqkt2eO2h2Z4ueKqCGKy4sXyLOYBJ9IhSkVInsCHhqiGQtbRrL2eTZ2hUYUIj5XeQgAULPDoVuG28yoVUZPuKnmKlmtpQOD7r2XvtPwz2sSSo6T34E57HkouXjX0eqGMjc17o3X4OC5WTlMhjMNfV55hqvlfSf44PNXa8TpNbsu7pRAjV6BHktUPzBxRrVI8d3ZVbDzrLlNu3nEFFrov09kZRH1C6zXtJZOlL13wFCgcUWeKsGR030xniLtSsf3otYvbztO5k2Ftbilw4axjm0gy0yiWiSydtBRPSPBtz2TKoZ9W1s2PbnikTfAEcbnOipWQW3VXsLw3YhTQ4c5SiFHdD8oNlzuZndu6h3zx01uIIXOFUFyOlmXTPx7Do1PjliNsVkE9LWEOO0nwEnjpx19iLwajEIZGKpcuMCDJCpCkpB7gEZjBetsxMNpduSGcz0GypryCcEajXNmwYmeJhPPiVy3c6TuuTID89rPSJKPKXMv00k422H3OuTz9lKiWR3PzCFo5MZE2EpsybO4rwdaHkpBRer1zq3sgFgh4hnEz9AfGTIzXV3g8wrI3kxBRdMh8DKEW6USheObMpk3wKtrQt8UYuRwVtdgSkTBFPenpbUZ5ZqsMwRmJP7EJU0UzmCEExhRngm4zX0uC4eQizUgV28rRxxWLEQd5NCsaCCRQIuC7S9yzDuAmGvbRbgX6IinyUcxI8zMaIoRALglB7Imb08RsBMLgo0IUSVH4Uno9DZjuxsALrlkbaEc8eZRZFlOHynh6sG8i4hBLYFXbMun0yhq19zM9LCnA6DpCO0blofdi9GRuY5YusxTja6kbvTFID6lA6aNkkStN88LoDZnQAkXBkfSZWIe7k5iooJztcWI0MKc6ftKDDlEclr8hRsIYcm9r5NQOUjfGRzJchMeej0bp2kkHlOi8tU9nRODT3f0ZdLnfn4aXF3JdPMMTEDRn13Rw53gZFxAv3a6wCRtYl64qHrRXrn5UhAFpC8pFapo998kHmuMUFguL2BYeznFv9HNh9MnZNqoOVn5HhML2maHsXymoEcP0iznvrIfoRE6IwHFQJQ8xDhKOAFf4qtBESxnCsSwXp5qr17g2MDg98XOEaW2rcdZFgHiOWMSNAsysqgZz4XyJohu7l2EaPMQhkGKgPQMvXzTN5h7T52M2vJOtiXO3504jJd09168YqNkXMWch6Lvrk9jwM6Ak81gxnTu2ZviSkPGjZmTlLbM3ruDWtZiOq3VCLAYpFLfpUfmDPyqDTUbxmOdmnc2dOSvs728cSyBWGmnHSSf8184KUmplmmxMhFyJA2AvymO5QtlWM6RKKwvrx2trkzuo8JSliv3USG4GcjSTvO6YxG5qeJYIslK9lhXMLdJF0mZ2vWHG6X1c4P5uwNeukv38jSvlBaS5BIXHEcvgnsS95MLhe283DciA8BMeyWmZhLN27pDFz3peaIcwMtypWShyHHb3qWMSWTGe1vzN62ko4yCrDzCJUfM0sGfYbfZe68HD5vEAFWaobpxfz17zpi2VwQ3yxiIyaEUaOyxUN3A27curVniAMuu5TySPk5qOEgHzQWNU7li3hO7ob80llU9McD2geG7jmdVIGffWtCB308nXAhQbhtPh1x7E12WcRfHtD4CrykmtrbnjoSHMpp7zdcv3NNMisddHnDHfkH9geE7Sl3Q2n892tgMceOG6TyfeFWGEk6ukSDmaqYDddMuPwwLtNMM2aTIaVRF8pWAFpmPfqH3HN5hcQPZLmN67jhhNlCYEk5XQXoKfxOZwq0lK4TSkt2SofrFzjbCGbBpPZSdxv4INkrmwVv99tW6GbiYiUp88dSxYhz3GcVknRPj7jnmMNvoBFSVAGAPQCgUeuiaUU8x6HTvIZJ1wAY919TwkTLMOvpsVLZuJheOaPtuefv9zzbG1slUOIIy3OYcU3gmXikjH6uQ1KaLt0BwFrtGQ7haTVnXI51KM3Gj5YxfjYFEfkSLNeR94Rf2MER1kkxMni8wakuXmLvCZz1tqOvtQL4N7CeOPYs3MZrhgcYzDmO4YKugfKibxZpzsvmGkjebwTLI3Iv4QtJpZnDZdaRJpv2TXZ7Huscj8U5z2KDrwdDVKluQuJfLYEV9Q2dw5jaEmVc8b9IX2U3hAbJjLPfpmzadAa5GyXRHFUH1bDhguNPqOCDhs7g3CLs7PQOVR3cDvDVJhjACury49FlOGxlDGxxeNEtOxlZYb7KqyDMF80bX4TfJWCKfxSXxlKpJKuYH8ZCbJc5drqHbUvYZTQeJtWY9VVFxaqTCBPhgTTRG37YDWAhOOSYE2JUGEl9Dnl0LZFCv9TsIggz92qEQ4TvrQTMyBNbArOdgSz4QqDbMpspzTqac50h9HW6x1QeoeAl03MpS0Z36rZvnVcG8KNHPRptPYJhougk3cXvW6nAG0P5AyQtAry1hGa6ifrAYdOSXNkI0jsOVqPeIG3nytDthymI1TcAFQf8QYlrmI2WJp234aQGpDrHEVepn5iBfUsijbiTF5NI0VZUPrR5uRFHVoD9zZNa4xZ7KxBaTz8hRwuV0E4mdC34T9ojBgir07Tr7XkMqssA5K02ip7fOtBPZEhMLZoWjzyNRB0icawWRg9DG4LClrbko70S9zVq73AmiaR9sX9hC1CnndDLBz3PCuy6hmN1RV4MS5Qm89cOEFxWCtBKbaQFsmAe9TvqoFkIMB0PNwyHUdm5oxHfsZxSYkUjwtEWPjr4V5HwWdj618M0W1qP5uP3z13L7UbPDnDKCub6koCtrbSWwmJSpKxpKeIavRjmi7DICmMTUD0JPUquBQ4sKgkq10hJffRF6cVuizzUQWwrURyuI462Z0SvqrFIiCA36vZn0qhWM1cZ5DtvmQnisfQPzRU0gKrZwSSZNEJq0i5MiGt6E4eTcwXTmWB9FLQy9QsxhLSGjyi99sIDNQLw1Scw0RWHjXYLOjrNjj9sHAddqFKHiuMZ6BAUyvaUtRgzVRDJLcSHsVltIE4r7nYe2eM89vb1iywgqOcs7zDkVTOKbIz3QzzL4jWtaS0yKQnm49hzJBdtsfxuN1b100T5TEaeLCD7QT2SMAgELDC4ieJTjJxRKgV7vrUhafjeS56yKo8vkA0Y0YpMqyihI7HmC1gyZ6BSkenRR8w2VGEuMArWEyemZVsx0kaRY77WTbHHsoZAr0YdQDTVLm6ksIdTrgrYkKGyZevb4EJBm5GfufoycMM93RrRzxbNpTCKdxpqX1WNUMG70fm6xdaMaxxpsKH8BulFwaPLSKfP82SNKkiLie4jbd7yGDro7IvEs5ALojQ16VcQKWcwQGtxEH7OApR0SXGSCWF4nsAzj6tc9uuJjM04Tx2iFkDSl4YqYnOsPaChiGvhX9x4IijdkWzQIy9E4EBbtr5Rb0Iczp5nz5h9tzawRYmDtvOUoJKSxUSUmQ57U4mjcuMOgoCvKXXVYqjMWJW8H4SwI92Ag4vgyAtczhqqcdQS6TJWL773wGzZ3IjmzzYSNTTs6M7jIUYFxUGh5xJvDWd34V2mXTFd2ErB1trUVlYZWgDl452qV2Q1Gt51hCtLoJn5NEzoXkLSQuiv7klKjipttSy0UP9ftxOHBGWhNKtLhblQUfVasIPugN8OcKdKcRdOhrdf4rs31JwV3ajj5SAcyOLulqWpJRvMkOhMq9c6Fjr5TfLKCaUFA3LQW4x1ga4IH70HPFBvDyLM7iMn33V0pSlu6TMYBnDRzEsa9mjqNy8OlQM6QQJE5N4Zo7lkheo00sfjAJqEGTIIpmNTihFNhmrwGrCQO6pxnezdZ91yfSHiqS0a056XPBNKn4oX2gIXaFrFgARQLln0GwEJi4BB91GPgiWZbtSGEM9UfcREMVnbsLLoPF0RAP5f6A6G2MNdy9lHyvCJh4edG0WWCao7GluJqAeRUuicfTXlGN3oRbdF1icJT713pNv3DtkC45w4PzI7t6oFHzvjlgZHJl9s9zAPjGa5rAhDmC9Z5OjmIvZ77v7FE4xYTGGe4BBIgDsZ8gmhuW3p1X8vrqnYYHlvnC1GWIOl2oduY2bFYO6b48746ik6ov2PinuetpjZyhUW0Jw3dhWJeucUbhGWV8EyJW0cyT2HoTABc90yIDn9r7BsBFR3MtYnFu1YD7rPbajFn4gvYXNchbkUPurOw4MMLSQ7YgJ1NBxYpJCE6VC4gOUmZTDnCzfQgSArdH75S0rpnShYGb3D9Ajboso1YPL8bxNwZoSWFzjyaBoXRegQzqC2CQalZwhcTrvgEXduM57qtcm9x3XBD7pcbFvDcCggJ6sCmIadP37RPSlcR5tSiZKMLp0mr7hQhE8r36r2t2oPrIQ6AON9B30tIu2FJlFGxZMmLS0sgEraoz5isEIVG6ITb7ZCfYr6jBqas1t5okBMi9nYgNCsCEhDkwNwU1Ha1qt4jbVa0unK7OkeXtcA8vNshDnXWpJunnGWML3gOMQr1JlZnxAAnswa49kn8HagCkM0kfZPlGkdnVI6pkAEcqs8nVcvX3IdLoQpvmli28PE8gsSnd3fbMgOwAfjisHMOt4P1j6jLDLRjiTPAXrk5AqhWx0zdJAjc36CJM3Wj3jJI2ydeUwyVChSDWugXQ5uUIH56FmV3vI5Z9UKSdKggQXBvysbxJTWOc9TTmt6sS0iOzk8z8ZkkOvLbQpSCRHb1Z3Fp2g16z6ZSd59exyKTRnyeW6Yti14TNVFoU0euvcTtHThPrG8sU1QtyJsvAtTcoLaeaSKdlZ3xcxHxbnzgDogcq8aLxqBf7JjRc1RgEU4s8fEZLTMQSFNhAjXPz41dEDupMZ5TNpxjiqGLFx3enJZouD8P56bxrrn5WsXC9WoZKqnjkJyEjfd46d6o4dGfBZAPhzMzjYHz5vPaAX0Ju54yHWDTBt8DnQS0uTIctSTcz55Tp6lzrM7hZSxuzZwDJN8gVT3l25JlVl91si6pvvwU1SnwpUxbjwssgal91C6IHprAkuPCxKlBPOtCNu0NLDAkPBObArzT27TrtUukisI7copGbua2109VYegWgEFXdkGdX16Git4NpdpIWKMImOGtri76mRhgNXKrwbueRbsr3NT7xoCII6hurqVPdn8wdFNN7k2kDWiPfmtdNKPTGOLfwgxdSS6eDatRhpmsfqFPP3LYnBUcZk2RV2lP4QWPmu9YCpfYdxEDGMbKIYumJi6iKw9THAmsAXKWyR782ncczTolarKgzcwTkfkHBIVBa7IARWcUzjTxSHfKwtG8SHubFaqE7rGlSEuK4esjyebIPxGxzUv1rKiksox3DgnOqGsG1J8JRcc0zTZlHS4F6wE0n23CoSbAyxmqRcmvDTM8SeXPqh12bdQY27CIgWdxIkQvHHjpipyMJ6Wnt7KGegnlNOJ8xx3bBkDhmNEKjjVi7BwzxBH5qnGhD2c6IWxGTeHe43Tgsd3p1dDR1S7A4s1P3q6NY6LWNahTehcFwh7cuMWyzfV9sw7EuW8oXKqTh1MxkxSdQiOBlmjoe5YtlyAZXLSzzSEMuvsUreKzKBIsq6vzJUDMwOB4lK5t9O2onv5dLwkzsYo2Nt8hJqbA8pGC3inIryKCCqRNrKIHEJy44DqfnCFgps9qo6CUj1dpsu3dqWXUdOLD95uO2loPqx22fMx3YNYOe3RtEOcpzUsRxgQYNXjtEB3shb0QmjXZ8sPOznw7otcq4eEPOTKnuBNsRt8odE9SoFlkCPECzi8sfuSiqEct9wTDmCMhEjBNTHTZotgBXWPiu1PwH9oixOH0fxAaKhhImbsv5wqaV5OLvXsYvchoQSZEFrggltzBkPNDR1YHDPnOtMmgrL80vsAExQHUHi6sHil2pEh5C9uEDTiH8pu0mTzX9L5XM50arGCikDdZZU8EsOpKgLNBPTMGWJR9Y2MLagihcd0QUs38ri1s9UTpwFOmRL3c6o9pr7FxVedXXIt1j3A2dpiv1RWnUgbcOBkRLcv88s6WlaAK4K0TsmiNFCITUHi8HE4x5VJBxkoeeXAOfii0dUsMgxYOGWukbwXBYuH4iZtY8VYm9kLOZuWN9tWiObgDH7rx6qlP9qsEm5gKwSmWMjZSkAGlMhNX1hWNLhs5uGpr9MhWQaoCWZUyB2ShzbPIpW9saoevtRBnc70OoaH0rcAASMoHfCXiEuEaVOEHJoH2LEH1q5Q7bFUklsHgXMys3HLDo3yxjqPSIAKJ21sKtYfHwWybLrL7Oo9WSoDANkKeAH7galcA4eWjZwuyE53bmad6B9zUHavSNIuYm1enIjz99Wc2zNRaUpR6Q01jCqM25BbMQBx04945GWDWlXM5GIE07vkbnJBwj4rPxLhEh8In9QuhwMA0McB5jjDsvkbHXd1FKcu6iK2rNVp1GdyAYquqnkixewd80iKqvbQ2SN0bBmlNDtJ0pTq1j3rndJyjusOH3zukZ70gNByuXxAfvtt698Cm8MIIpLAo70wdibEHOJqrMCx23BYudR7HGuOUp2HtMUvgEhdOTUZU01pwbe1IDfv15D3VQpwMpqg5LHi6JqYv0h8j7YQrcK2WTmIQiRLZW9axW7EzjuhlfRnCX7VOejCQqL8C3zsAB7CbgXUEmnpf0BQvsQVSCMX6RQukYnZzDzZJFn1ZSzPaa8qdJq0Ov36MjwsJn2SJ9Q6Hg6tEzIqpgOYSWWAHi5UscZbq0mHlPJEHhRYvdAzVRi9qphc1ePI6uj77ZgU4sCbeMycxNuRa0iB6WCqVd7FB3zG391aKNEjym46TngQebFYMYBwnDXuCN03nnhieut6zN5SwGODFX8WfEycmV8nGRzvTJJBNd3DPbdPk9qS2ayyUewkSgB31OifTlPQrpH4zsBj6Gcrms7hzyyzmW404FVLbI6HMEgH4C2PcH2rYNG5IXWO9MdZEo2tVUAMOOeE4I3eJ0od7kohfgktiQ3d4WW0zSLNwbFvuVkbKNSLMby5sQGrBys9UOKiWk347dsa2N8kYcjgsgfe6

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída! Abaixo está evidenciado o resultado do teste:


  24314 passing (45s)
  2 failing

  1) OpenAPI - MovementPeriodStatus_v1_000.json  - Schemas:  should contain the same Id property name in URL and body:

      Check the endpoint '/movementPeriodStatus/{code}'. It may be a typo or case sensitive difference
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:165:97)

  2) OpenAPI - MovementPeriodStatus_v1_000.json  - xtotvs:   - paths:  should contain 'available' inside productInformation, inside 'paths':

      At path '/movementPeriodStatus/{code}', method 'get'.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:268:111)



npm ERR! Test failed.  See above for more details.
travis_time: end:003b8f29:start=1552482391625881791,finish=1552482437669948160,duration=46044066369

Para maiores detalhes acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/505750509

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída! Abaixo está evidenciado o resultado do teste:


  24315 passing (33s)
  1 failing

  1) OpenAPI - MovementPeriodStatus_v1_000.json  - xtotvs:   - paths:  should contain 'available' inside productInformation, inside 'paths':

      At path '/movementPeriodStatus/{movementPeriodStatusCode}', method 'get'.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:268:111)



npm ERR! Test failed.  See above for more details.
travis_time: end:09089318:start=1552482883727007837,finish=1552482916992680701,duration=33265672864

Para maiores detalhes acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/505754127

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída! Abaixo está evidenciado o resultado do teste:


  24316 passing (35s)

travis_time: end:0ad82b2a:start=1552485074904268120,finish=1552485110134527417,duration=35230259297

Para maiores detalhes acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/505771793

**Comment by fabianopimpao** [comment]
Bom dia,

Após avaliar juntamente com o PO do módulo, verificamos que não há necessidade de disponibilizar as API's destes Pull Requests. Portanto podem ser excluídos todos os mesmos.

Atenciosamente,
WILLIAM SILVESTRE / SEGMENTO SAÚDE

**Pull request closed without merging**
