### PR TITLE
Criando a API ProductionAppointment

### PR DESCRIPTION
**Pull request by michellerhen**
Criação da nova API ProductionAppointment.

### CODE REVIEW

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída! Abaixo está evidenciado o resultado do teste:


  25616 passing (53s)
  3 failing

  1) OpenAPI - ProductionAppointment_v2_000.json  - Schemas:  should contain the same Id property name in URL and body:

      Check the endpoint '/ProductionAppointment/{CompanyId}/{ProductionOrderNumber}/{AppointmentType}'. It may be a typo or case sensitive difference
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:169:97)
      at processImmediate (internal/timers.js:439:21)

  2) OpenAPI - ProductionAppointment_v2_000.json  - Schemas:  should have 'hasNext' when it's an 'getAll' endpoint:

      At endpoint '/ProductionAppointment', must have hasNext and pagination mechanism.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:192:86)
      at processImmediate (internal/timers.js:439:21)

  3) OpenAPI - ProductionAppointment_v2_000.json  - Parameters:  should use common parameters:

      AssertionError: Please check this endpoint|httpverb: /ProductionAppointment|get: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:215:90)
      at processImmediate (internal/timers.js:439:21)



npm ERR! Test failed.  See above for more details.
travis_time: end:09ab43b6:start=1557940021753005689,finish=1557940075309343323,duration=53556337634

Para visualizar o log com detalhes da validação que foi realizada, acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/532917232

Caso queira entender melhor cada uma das validações e formas de correção, visite nossa documentação: http://tdn.totvs.com/pages/viewpage.action?pageId=465388996

**Comment by michellerhen** [comment]
Revalidar a API

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída! Abaixo está evidenciado o resultado do teste:


  25616 passing (24s)
  3 failing

  1) OpenAPI - ProductionAppointment_v2_000.json  - Schemas:  should contain the same Id property name in URL and body:

      Check the endpoint '/ProductionAppointment/{Company}/{ProductionOrderNumber}/{AppointmentType}'. It may be a typo or case sensitive difference
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:169:97)
      at processImmediate (internal/timers.js:439:21)

  2) OpenAPI - ProductionAppointment_v2_000.json  - Schemas:  should have 'hasNext' when it's an 'getAll' endpoint:

      At endpoint '/ProductionAppointment', must have hasNext and pagination mechanism.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:192:86)
      at processImmediate (internal/timers.js:439:21)

  3) OpenAPI - ProductionAppointment_v2_000.json  - Parameters:  should use common parameters:

      AssertionError: Please check this endpoint|httpverb: /ProductionAppointment|get: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:215:90)
      at processImmediate (internal/timers.js:439:21)



npm ERR! Test failed.  See above for more details.
travis_time: end:017406aa:start=1557942674358361199,finish=1557942698563847124,duration=24205485925

Para visualizar o log com detalhes da validação que foi realizada, acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/532935793

Caso queira entender melhor cada uma das validações e formas de correção, visite nossa documentação: http://tdn.totvs.com/pages/viewpage.action?pageId=465388996

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída! Abaixo está evidenciado o resultado do teste:


  25616 passing (50s)
  3 failing

  1) OpenAPI - ProductionAppointment_v2_000.json  - Schemas:  should contain the same Id property name in URL and body:

      Check the endpoint '/ProductionAppointment/{Company}/{ProductionOrderNumber}/{AppointmentType}'. It may be a typo or case sensitive difference
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:169:97)
      at processImmediate (internal/timers.js:439:21)

  2) OpenAPI - ProductionAppointment_v2_000.json  - Schemas:  should have 'hasNext' when it's an 'getAll' endpoint:

      At endpoint '/ProductionAppointment', must have hasNext and pagination mechanism.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:192:86)
      at processImmediate (internal/timers.js:439:21)

  3) OpenAPI - ProductionAppointment_v2_000.json  - Parameters:  should use common parameters:

      AssertionError: Please check this endpoint|httpverb: /ProductionAppointment|get: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:215:90)
      at processImmediate (internal/timers.js:439:21)



npm ERR! Test failed.  See above for more details.
travis_time: end:024d10b8:start=1557944728871278394,finish=1557944779715564226,duration=50844285832

Para visualizar o log com detalhes da validação que foi realizada, acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/532949664

Caso queira entender melhor cada uma das validações e formas de correção, visite nossa documentação: http://tdn.totvs.com/pages/viewpage.action?pageId=465388996

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída! Abaixo está evidenciado o resultado do teste:


  25617 passing (50s)
  2 failing

  1) OpenAPI - ProductionAppointment_v2_000.json  - Schemas:  should contain the same Id property name in URL and body:

      Check the endpoint '/ProductionAppointment/{Company}/{ProductionOrderNumber}/{AppointmentType}'. It may be a typo or case sensitive difference
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:169:97)
      at processImmediate (internal/timers.js:439:21)

  2) OpenAPI - ProductionAppointment_v2_000.json  - Parameters:  should use common parameters:

      AssertionError: Please check this endpoint|httpverb: /ProductionAppointment|get: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:215:90)
      at processImmediate (internal/timers.js:439:21)



npm ERR! Test failed.  See above for more details.
travis_time: end:04ba2a80:start=1557945038338728129,finish=1557945089065222618,duration=50726494489

Para visualizar o log com detalhes da validação que foi realizada, acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/532951772

Caso queira entender melhor cada uma das validações e formas de correção, visite nossa documentação: http://tdn.totvs.com/pages/viewpage.action?pageId=465388996

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída! Abaixo está evidenciado o resultado do teste:


  25619 passing (53s)

travis_time: end:08ad740f:start=1558009654925137101,finish=1558009707954363410,duration=53029226309

Para visualizar o log com detalhes da validação que foi realizada, acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/533297938

Caso queira entender melhor cada uma das validações e formas de correção, visite nossa documentação: http://tdn.totvs.com/pages/viewpage.action?pageId=465388996

**Pull request merged**
