### PR TITLE
correcting comment posting script

### PR DESCRIPTION
**Pull request by reisaolucas**

### CODE REVIEW

**Comment by reisaolucas** [comment]
A validação foi concluída! Abaixo está evidenciado o resultado do teste:


  19528 passing (46s)
  1 failing

  1) SCHEMA - AccountantAccount_2_000.json  - Required:  should have every element of the 'required' array as a property:

      Schema has 'PostingNature' as a required type (at 'BusinessContentType'), but it does not exist as a property.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testSchema.js:110:146)



npm ERR! Test failed.  See above for more details.
travis_time: end:00e9eab8:start=1550238501999506042,finish=1550238548249840540,duration=46250334498

**Comment by reisaolucas** [comment]
A validação foi concluída! Abaixo está evidenciado o resultado do teste:


  19528 passing (22s)
  1 failing

  1) SCHEMA - AccountantAccount_2_000.json  - Required:  should have every element of the 'required' array as a property:

      Schema has 'AnalyticalOrSynthetic' as a required type (at 'BusinessContentType'), but it does not exist as a property.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testSchema.js:110:146)



npm ERR! Test failed.  See above for more details.
travis_time: end:04072d40:start=1550520413877306236,finish=1550520436119097186,duration=22241790950

Para maiores detalhes acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/495086956

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída! Abaixo está evidenciado o resultado do teste:


  19528 passing (22s)
  1 failing

  1) SCHEMA - AccountantAccount_2_000.json  - Required:  should have every element of the 'required' array as a property:

      Schema has 'AnalyticalOrSynthetic' as a required type (at 'BusinessContentType'), but it does not exist as a property.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testSchema.js:110:146)



npm ERR! Test failed.  See above for more details.
travis_time: end:04072d40:start=1550520413877306236,finish=1550520436119097186,duration=22241790950

Para maiores detalhes acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/495086956

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída! Abaixo está evidenciado o resultado do teste:


  19528 passing (22s)
  1 failing

  1) SCHEMA - AccountantAccount_2_000.json  - Required:  should have every element of the 'required' array as a property:

      Schema has 'AnalyticalOrSynthetic' as a required type (at 'BusinessContentType'), but it does not exist as a property.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testSchema.js:110:146)



npm ERR! Test failed.  See above for more details.
travis_time: end:04072d40:start=1550520413877306236,finish=1550520436119097186,duration=22241790950

Para maiores detalhes acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/495440360

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída! Abaixo está evidenciado o resultado do teste:


  19528 passing (28s)
  1 failing

  1) SCHEMA - AccountantAccount_2_000.json  - Required:  should have every element of the 'required' array as a property:

      Schema has 'AnalyticalOrSynthetic' as a required type (at 'BusinessContentType'), but it does not exist as a property.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testSchema.js:110:146)



npm ERR! Test failed.  See above for more details.
travis_time: end:0b9c0340:start=1550581511243858774,finish=1550581539321306687,duration=28077447913

Para maiores detalhes acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/495443417

**Pull request merged**
