### PR TITLE
JSON de Coparticipação para homologação: BeneficiariesCoparticipation

### PR DESCRIPTION
**Pull request by JamesSilveira**
JSON de Coparticipação para homologação: BeneficiariesCoparticipation

### CODE REVIEW

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída!

Favor verificar os erros encontrados. 

Abaixo está evidenciado o resultado do teste:


  28604 passing (1m)
  16 failing

  1) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Filename:  should contain version (lowercase 'v'):

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:81:46)
      at processImmediate (internal/timers.js:439:21)

  2) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Content Format:  should be complient with OpenAPI in version 3.0':
     AssertionError: expected { Object ($schema, info, ...) } to have property 'openapi'
      at Context.<anonymous> (validator/test/testOpenAPI.js:91:47)
      at processImmediate (internal/timers.js:439:21)

  3) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Servers:  should have a 'servers' property with 'URL' and 'variables':
     AssertionError: expected { Object ($schema, info, ...) } to have property 'servers'
      at Context.<anonymous> (validator/test/testOpenAPI.js:98:47)
      at processImmediate (internal/timers.js:439:21)

  4) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Servers:  should have an URL consistent with our model:
     TypeError: Cannot read property '0' of undefined
      at Context.<anonymous> (validator/test/testOpenAPI.js:104:61)
      at processImmediate (internal/timers.js:439:21)

  5) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Version:  should contain the same version on 'info' as in filename:

      AssertionError: expected 'eneficiariesCoparticipation.1_000' to equal '1.000'
      + expected - actual

      -eneficiariesCoparticipation.1_000
      +1.000
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:116:44)
      at processImmediate (internal/timers.js:439:21)

  6) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Endpoints:  should contain success responses for all http verbs:
     AssertionError: expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:136:73)
      at processImmediate (internal/timers.js:439:21)

  7) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Endpoints:  should have unique 'operationId':
     AssertionError: expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:146:108)
      at processImmediate (internal/timers.js:439:21)

  8) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Schemas:  should use external schemas for all requests and responses :
     AssertionError: expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:163:70)
      at processImmediate (internal/timers.js:439:21)

  9) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Parameters:  should have 'page', 'pagesize' and 'order' for collection endpoints:
     AssertionError: Please check this endpoint: : expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:214:120)
      at processImmediate (internal/timers.js:439:21)

  10) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Parameters:  should use common parameters:
     AssertionError: Please check this endpoint|httpverb: : expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:221:90)
      at processImmediate (internal/timers.js:439:21)

  11) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Errors:  should use common errors schema:
     AssertionError: expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:243:67)
      at processImmediate (internal/timers.js:439:21)

  12) OpenAPI - BeneficiariesCoparticipation_1_000.json  - xtotvs:   - paths:  should contain xtotvs/productinformation as an array inside 'paths':
     AssertionError: Please check this endpoint|httpverb: : expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:253:89)
      at processImmediate (internal/timers.js:439:21)

  13) OpenAPI - BeneficiariesCoparticipation_1_000.json  - xtotvs:   - paths:  all products declared inside 'info' should also exist inside paths' x-totvs:

      X-Totvs inside 'info' has 'PROTHEUS' as product, but it's not declared inside 'paths'.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:270:128)
      at processImmediate (internal/timers.js:439:21)

  14) OpenAPI - BeneficiariesCoparticipation_1_000.json  - xtotvs:   - info:  product name should be standardized:

      You passed 'PROTHEUS' as x-totvs product, but we already got 'Protheus'.
      + expected - actual

      -PROTHEUS
      +Protheus
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:306:111)
      at processImmediate (internal/timers.js:439:21)

  15) OpenAPI - BeneficiariesCoparticipation_v1_000.json  - Schemas:  should be dereferenced. This means all external references are correct (FilePaths and Object property names):
     AssertionError: Error: Error downloading https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/events/BeneficiariesCoparticipation_1_000.json 
HTTP ERROR 404: expected false to be truthy
      at Context.<anonymous> (validator/test/testOpenAPI.js:167:59)
      at processImmediate (internal/timers.js:439:21)

  16) OpenAPI - BeneficiariesCoparticipation_v1_000.json  - xtotvs:   - info:  product name should be standardized:

      You passed 'PROTHEUS' as x-totvs product, but we already got 'Protheus'.
      + expected - actual

      -PROTHEUS
      +Protheus
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:306:111)
      at processImmediate (internal/timers.js:439:21)



npm ERR! Test failed.  See above for more details.
travis_time: end:1c9beb98:start=1569419328342222871,finish=1569419391424679214,duration=63082456343,event=script

Para visualizar o log com detalhes da validação que foi realizada, acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/589458573

Caso queira entender melhor cada uma das validações e formas de correção, visite nossa documentação: http://tdn.totvs.com/pages/viewpage.action?pageId=465388996

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída!

Favor verificar os erros encontrados. 

Abaixo está evidenciado o resultado do teste:


  28710 passing (1m)
  16 failing

  1) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Filename:  should contain version (lowercase 'v'):

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:81:46)
      at processImmediate (internal/timers.js:439:21)

  2) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Content Format:  should be complient with OpenAPI in version 3.0':
     AssertionError: expected { Object ($schema, info, ...) } to have property 'openapi'
      at Context.<anonymous> (validator/test/testOpenAPI.js:91:47)
      at processImmediate (internal/timers.js:439:21)

  3) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Servers:  should have a 'servers' property with 'URL' and 'variables':
     AssertionError: expected { Object ($schema, info, ...) } to have property 'servers'
      at Context.<anonymous> (validator/test/testOpenAPI.js:98:47)
      at processImmediate (internal/timers.js:439:21)

  4) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Servers:  should have an URL consistent with our model:
     TypeError: Cannot read property '0' of undefined
      at Context.<anonymous> (validator/test/testOpenAPI.js:104:61)
      at processImmediate (internal/timers.js:439:21)

  5) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Version:  should contain the same version on 'info' as in filename:

      AssertionError: expected 'eneficiariesCoparticipation.1_000' to equal '1.000'
      + expected - actual

      -eneficiariesCoparticipation.1_000
      +1.000
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:116:44)
      at processImmediate (internal/timers.js:439:21)

  6) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Endpoints:  should contain success responses for all http verbs:
     AssertionError: expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:136:73)
      at processImmediate (internal/timers.js:439:21)

  7) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Endpoints:  should have unique 'operationId':
     AssertionError: expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:146:108)
      at processImmediate (internal/timers.js:439:21)

  8) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Schemas:  should use external schemas for all requests and responses :
     AssertionError: expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:163:70)
      at processImmediate (internal/timers.js:439:21)

  9) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Parameters:  should have 'page', 'pagesize' and 'order' for collection endpoints:
     AssertionError: Please check this endpoint: : expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:214:120)
      at processImmediate (internal/timers.js:439:21)

  10) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Parameters:  should use common parameters:
     AssertionError: Please check this endpoint|httpverb: : expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:221:90)
      at processImmediate (internal/timers.js:439:21)

  11) OpenAPI - BeneficiariesCoparticipation_1_000.json  - Errors:  should use common errors schema:
     AssertionError: expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:243:67)
      at processImmediate (internal/timers.js:439:21)

  12) OpenAPI - BeneficiariesCoparticipation_1_000.json  - xtotvs:   - paths:  should contain xtotvs/productinformation as an array inside 'paths':
     AssertionError: Please check this endpoint|httpverb: : expected undefined to be true
      at Context.<anonymous> (validator/test/testOpenAPI.js:253:89)
      at processImmediate (internal/timers.js:439:21)

  13) OpenAPI - BeneficiariesCoparticipation_1_000.json  - xtotvs:   - paths:  all products declared inside 'info' should also exist inside paths' x-totvs:

      X-Totvs inside 'info' has 'PROTHEUS' as product, but it's not declared inside 'paths'.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:270:128)
      at processImmediate (internal/timers.js:439:21)

  14) OpenAPI - BeneficiariesCoparticipation_1_000.json  - xtotvs:   - info:  product name should be standardized:

      You passed 'PROTHEUS' as x-totvs product, but we already got 'Protheus'.
      + expected - actual

      -PROTHEUS
      +Protheus
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:306:111)
      at processImmediate (internal/timers.js:439:21)

  15) OpenAPI - BeneficiariesCoparticipation_v1_000.json  - Schemas:  should be dereferenced. This means all external references are correct (FilePaths and Object property names):
     AssertionError: Error: Error downloading https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/events/BeneficiariesCoparticipation_1_000.json 
HTTP ERROR 404: expected false to be truthy
      at Context.<anonymous> (validator/test/testOpenAPI.js:167:59)
      at processImmediate (internal/timers.js:439:21)

  16) OpenAPI - BeneficiariesCoparticipation_v1_000.json  - xtotvs:   - info:  product name should be standardized:

      You passed 'PROTHEUS' as x-totvs product, but we already got 'Protheus'.
      + expected - actual

      -PROTHEUS
      +Protheus
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:306:111)
      at processImmediate (internal/timers.js:439:21)



npm ERR! Test failed.  See above for more details.
travis_time: end:280793c4:start=1569423280893885723,finish=1569423345080293460,duration=64186407737,event=script

Para visualizar o log com detalhes da validação que foi realizada, acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/589491977

Caso queira entender melhor cada uma das validações e formas de correção, visite nossa documentação: http://tdn.totvs.com/pages/viewpage.action?pageId=465388996

**Comment by marlongoncalves** [comment]
Ajustado, favor validar.

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída!

Favor verificar os erros encontrados. 

Abaixo está evidenciado o resultado do teste:


  28919 passing (1m)
  2 failing

  1) OpenAPI - BeneficiariesCoparticipation_v1_000.json  - Schemas:  should be dereferenced. This means all external references are correct (FilePaths and Object property names):
     AssertionError: Error: Error downloading https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/BeneficiariesCoparticipation_1_000.json 
HTTP ERROR 404: expected false to be truthy
      at Context.<anonymous> (validator/test/testOpenAPI.js:167:60)
      at processImmediate (internal/timers.js:439:21)

  2) OpenAPI - BeneficiariesCoparticipation_v1_000.json  - xtotvs:   - info:  product name should be standardized:

      You passed 'DATASUL' as x-totvs product, but we already got 'Datasul'.
      + expected - actual

      -DATASUL
      +Datasul
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:306:111)
      at processImmediate (internal/timers.js:439:21)



npm ERR! Test failed.  See above for more details.
travis_time: end:00e0d7bc:start=1572441491093091487,finish=1572441560878136013,duration=69785044526,event=script

Para visualizar o log com detalhes da validação que foi realizada, acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/604966252

Caso queira entender melhor cada uma das validações e formas de correção, visite nossa documentação: http://tdn.totvs.com/pages/viewpage.action?pageId=465388996

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída!

Favor verificar os erros encontrados. 

Abaixo está evidenciado o resultado do teste:


  28920 passing (28s)
  1 failing

  1) OpenAPI - BeneficiariesCoparticipation_v1_000.json  - Schemas:  should be dereferenced. This means all external references are correct (FilePaths and Object property names):
     AssertionError: Error: Error downloading https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/BeneficiariesCoparticipation_1_000.json 
HTTP ERROR 404: expected false to be truthy
      at Context.<anonymous> (validator/test/testOpenAPI.js:167:60)
      at processImmediate (internal/timers.js:439:21)



npm ERR! Test failed.  See above for more details.
travis_time: end:3950f9a0:start=1572442005059880732,finish=1572442033540725115,duration=28480844383,event=script

Para visualizar o log com detalhes da validação que foi realizada, acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/604969570

Caso queira entender melhor cada uma das validações e formas de correção, visite nossa documentação: http://tdn.totvs.com/pages/viewpage.action?pageId=465388996

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída!

Favor verificar os erros encontrados. 

Abaixo está evidenciado o resultado do teste:


  28920 passing (1m)
  1 failing

  1) OpenAPI - BeneficiariesCoparticipation_v1_000.json  - xtotvs:   - paths:  all products declared inside 'info' should also exist inside paths' x-totvs:

      X-Totvs inside 'info' has 'Protheus' as product, but it's not declared inside 'paths'.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (validator/test/testOpenAPI.js:270:128)
      at processImmediate (internal/timers.js:439:21)



npm ERR! Test failed.  See above for more details.
travis_time: end:07d3aaef:start=1572443331904016524,finish=1572443395758580614,duration=63854564090,event=script

Para visualizar o log com detalhes da validação que foi realizada, acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/604981081

Caso queira entender melhor cada uma das validações e formas de correção, visite nossa documentação: http://tdn.totvs.com/pages/viewpage.action?pageId=465388996

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída! 

Sua documentação foi aprovada em todos os casos de teste!

Para visualizar o log com detalhes da validação que foi realizada, acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/605021511

Caso queira entender melhor cada uma das validações e formas de correção, visite nossa documentação: http://tdn.totvs.com/pages/viewpage.action?pageId=465388996

**Comment by TTalkIntegracoes** [comment]
A validação foi concluída! 

Sua documentação foi aprovada em todos os casos de teste!

Para visualizar o log com detalhes da validação que foi realizada, acesse: https://travis-ci.org/totvs/ttalk-standard-message/builds/605140357

Caso queira entender melhor cada uma das validações e formas de correção, visite nossa documentação: http://tdn.totvs.com/pages/viewpage.action?pageId=465388996

**Pull request merged**
